[package]
name = "VibeChanger"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_14"] }

# Core library
relm4 = "0.9"
# Optional: reusable components
relm4-components = "0.9"
